import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import axios from 'axios'
import AuthProvider from '@/context/AuthContext'
import Protect from '@/components/protect'

const fontInter = Inter({
  variable: '--font-geist-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  axios.defaults.baseURL = 'http://localhost:3000'

  return (
    <html lang='en'>
      <AuthProvider>
        <Protect>
          <body className={`${fontInter.className} antialiased`}>
            {children}
          </body>
        </Protect>
      </AuthProvider>
    </html>
  )
}
